In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)





[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 =np.array([1,2,3,4,5,6])
arr2.reshape(3,2)  ## 3 row 2 column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
arr3 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1) ## from 0 to 10 skip element by 2 means 0,2, 4 ... upto 8 not includinhg 10


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matric
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## numpy vectoried operations
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

## element wise addition
print("Addition", arr1+arr2)

## element wise substraction
print("Substraction ", arr1-arr2)

## element wise multiplication
print("Multiplication", arr1*arr2)

Addition [11 22 33 44 55]
Substraction  [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]


In [15]:
## array slicing and example
arr = np. array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])
print("Array : \n", arr)


Array : 
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [16]:
arr[0]

array([1, 2, 3, 4, 5])

In [17]:
arr[0][0]

np.int64(1)

In [18]:
arr[1:] ## start from 2nd row till end of the row

array([[ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13]])

In [ ]:
arr[1:,2:]    ## 1 row 2 column 7 8  9\n 11 12 13

array([[ 7,  8,  9],
       [11, 12, 13]])

In [21]:
## mean and standard deviation
arr= np.array([1,2,3,4,5])
mean = np.mean(arr)
print(mean)
standard = np.std(arr)
print(standard)
norm_data = (arr-mean)/ standard
print(norm_data)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
