In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)





[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 =np.array([1,2,3,4,5,6])
arr2.reshape(3,2)  ## 3 row 2 column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
arr3 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1) ## from 0 to 10 skip element by 2 means 0,2, 4 ... upto 8 not includinhg 10


array([[0],
       [2],
       [4],
       [6],
       [8]])